default:
  # NOTE: options that apply to all the whitman data repos
  # are in data/config/private.yml
  # (solr_core, solr_path, solr_variables, etc)

  shortname: whitman-correspondence
  collection_desc: Correspondence for The Walt Whitman Archive
  tei_solr_xsl: collections/whitman-correspondence/scripts/solr_transform_tei.xsl
  # es_type:

  variables_solr:
    project: The_Walt_Whitman_Archive
    slug: whitman-correspondence
    site_url: https://whitmanarchive.org
development:
  variables_solr:
    project: The_Walt_Whitman_Archive
    slug: whitman-correspondence
    site_url: https://whitman-dev.unl.edu
# production:
  # production overrides here
