default:
  shortname: whitman-correspondence
  collection: whitman-correspondence
  site_url: https://whitmanarchive.org
  solr_core: api_whitman
  tei_solr_xsl: scripts/overrides/solr_transform_tei.xsl
  # tei_html_xsl: scripts/overrides/html_transform_tei.xsl
  tei_html_xsl: scripts/overrides/tei_to_html.xsl
  media_base: https://whitmanarchive.org/media
  variables_html:
    image_large: 1200
    image_thumb: 80
  api_version: "2.0"
  es_index: whitman-api_v2
  threads: 5

development:
  site_url: https://set_in_private_config
  solr_path: https://set_in_private_config/solr
  data_base: https://set_in_private_config/media

  variables_solr:
    project: The_Walt_Whitman_Archive
    slug: whitman-correspondence
    site_url: https://set_in_private_config

production:
  site_url: https://whitmanarchive.org
  solr_path: https://set_in_private_config/solr

  variables_solr:
    project: The_Walt_Whitman_Archive
    slug: whitman-correspondence
    site_url: https://whitmanarchive.org

grant:
  # NOTE: different collection name!!!
  collection: whitman-grant
  es_path: https://set_in_private_config/elastic
  es_index: api_v1_grant
  site_url: https://whitmanarchive.org

