default:
  shortname: whitman-correspondence
  collection: whitman
  site_url: https://whitmanarchive.org
  solr_core: api_whitman
  tei_solr_xsl: scripts/overrides/solr_transform_tei.xsl
  tei_html_xsl: scripts/overrides/html_transform_tei.xsl
  media_base: https://whitmanarchive.org/media

development:
  es_path: https://whitman-dev.unl.edu/elastic
  es_index: api_v1
  site_url: https://whitman-dev.unl.edu
  solr_path: https://whitman-dev.unl.edu/solr
  data_base: https://whitman-dev.unl.edu/media

  variables_solr:
    project: The_Walt_Whitman_Archive
    slug: whitman-correspondence
    site_url: https://whitman-dev.unl.edu

production:
  site_url: https://whitmanarchive.org
  solr_path: https://whitman-prod.unl.edu/solr

  variables_solr:
    project: The_Walt_Whitman_Archive
    slug: whitman-correspondence
    site_url: https://whitmanarchive.org

grant:
  # NOTE: different collection name!!!
  collection: whitman-grant
  es_path: https://whitman-dev.unl.edu/elastic
  es_index: api_v1_grant
  site_url: https://whitmanarchive.org
